"""Type stubs for rsshogi.book opening book types."""

from __future__ import annotations

from collections.abc import Callable

from rsshogi.core import Board, Move
from rsshogi.record import Record

class BookKey:
    @property
    def low(self) -> int: ...
    @property
    def high(self) -> int: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BookMove:
    def __init__(self, mv: Move, score: int, depth: int) -> None: ...
    @property
    def mv(self) -> Move: ...
    @property
    def score(self) -> int: ...
    @property
    def depth(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BookEntry:
    @property
    def key(self) -> BookKey: ...
    @property
    def moves(self) -> list[BookMove]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class YaneuraOuBookDiagnostics:
    @property
    def kind(self) -> str: ...
    @property
    def checked_rows(self) -> int | None: ...
    @property
    def complete(self) -> bool | None: ...
    @property
    def line_number(self) -> int | None: ...
    @property
    def previous_sfen(self) -> str | None: ...
    @property
    def current_sfen(self) -> str | None: ...
    def __repr__(self) -> str: ...

class YaneuraOuBookMove:
    @property
    def mv(self) -> Move: ...
    @property
    def ponder(self) -> Move: ...
    @property
    def score(self) -> int | None: ...
    @property
    def depth(self) -> int | None: ...
    @property
    def count(self) -> int | None: ...
    @property
    def comment(self) -> str: ...
    def __repr__(self) -> str: ...

class YaneuraOuBookEntry:
    @property
    def sfen(self) -> str: ...
    @property
    def min_ply(self) -> int: ...
    @property
    def comment(self) -> str: ...
    @property
    def moves(self) -> list[YaneuraOuBookMove]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class YaneuraOuBook:
    @classmethod
    def open(cls, path: str) -> YaneuraOuBook: ...
    def diagnostics(self) -> YaneuraOuBookDiagnostics: ...
    def validate_full(self) -> YaneuraOuBookDiagnostics: ...
    def lookup_sfen(self, sfen: str) -> YaneuraOuBookEntry | None: ...
    def lookup_position(self, board: Board) -> YaneuraOuBookEntry | None: ...
    def lookup_sfen_by_scan(self, sfen: str) -> YaneuraOuBookEntry | None: ...
    def __repr__(self) -> str: ...

class SbkDiagnostics:
    @property
    def duplicate_positions(self) -> int: ...
    @property
    def unresolved_next_states(self) -> int: ...
    def __repr__(self) -> str: ...

class SbkOpenProgress:
    @property
    def indexed_states(self) -> int: ...
    @property
    def total_states(self) -> int: ...
    def __repr__(self) -> str: ...

class SbkEval:
    @property
    def evaluation_value(self) -> int | None: ...
    @property
    def depth(self) -> int | None: ...
    @property
    def sel_depth(self) -> int | None: ...
    @property
    def nodes(self) -> int | None: ...
    @property
    def variation(self) -> str | None: ...
    @property
    def engine_name(self) -> str | None: ...

class SbkMove:
    @property
    def mv(self) -> Move: ...
    @property
    def raw_move(self) -> int: ...
    @property
    def evaluation(self) -> int | None: ...
    @property
    def weight(self) -> int | None: ...
    @property
    def next_state_id(self) -> int | None: ...
    def __repr__(self) -> str: ...

class SbkEntry:
    @property
    def state_id(self) -> int | None: ...
    @property
    def state_index(self) -> int: ...
    @property
    def sfen(self) -> str: ...
    @property
    def games(self) -> int | None: ...
    @property
    def won_black(self) -> int | None: ...
    @property
    def won_white(self) -> int | None: ...
    @property
    def comment(self) -> str | None: ...
    @property
    def moves(self) -> list[SbkMove]: ...
    @property
    def evals(self) -> list[SbkEval]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class SbkBook:
    @classmethod
    def open(cls, path: str) -> SbkBook: ...
    @classmethod
    def open_with_control(cls, path: str, callback: Callable[[SbkOpenProgress], bool | None]) -> SbkBook:
        """Open with progress; returning False cancels, None or True continues."""
        ...
    @property
    def author(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    def diagnostics(self) -> SbkDiagnostics: ...
    def lookup_sfen(self, sfen: str) -> SbkEntry | None: ...
    def lookup_position(self, board: Board) -> SbkEntry | None: ...
    def lookup_state_id(self, state_id: int) -> SbkEntry | None: ...
    def lookup_state_index(self, state_index: int) -> SbkEntry | None: ...
    def child_entry(self, parent: SbkEntry, move_index: int) -> SbkEntry | None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class MemoryBook:
    def __init__(self) -> None: ...
    def insert_move(self, key: BookKey, book_move: BookMove) -> None: ...
    def get(self, key: BookKey) -> BookEntry | None: ...
    def contains(self, key: BookKey) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class StaticBook:
    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> StaticBook: ...
    @classmethod
    def from_memory_book(cls, book: MemoryBook) -> StaticBook: ...
    @classmethod
    def from_file(cls, path: str) -> StaticBook: ...
    def to_bytes(self) -> bytes: ...
    def write_file(self, path: str) -> None: ...
    def get(self, key: BookKey) -> BookEntry | None: ...
    def contains(self, key: BookKey) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class BookBuilder:
    def __init__(self) -> None: ...
    def insert(self, key: BookKey, mv: Move, score: int, depth: int) -> None: ...
    def insert_for_position(self, board: Board, mv: Move, score: int, depth: int) -> None: ...
    def extend_from_game_record(
        self,
        record: Record,
        default_score: int = ...,
        default_depth: int = ...,
    ) -> None: ...
    def into_memory(self) -> MemoryBook: ...
    def build_static(self) -> StaticBook: ...
    def __repr__(self) -> str: ...

def book_key_from_position(board: Board) -> BookKey: ...
def book_key_after(board: Board, mv: Move) -> BookKey: ...
def book_builder_from_game_record(
    record: Record,
    default_score: int = ...,
    default_depth: int = ...,
) -> MemoryBook: ...

__all__ = [
    "BookKey",
    "BookMove",
    "BookEntry",
    "YaneuraOuBookDiagnostics",
    "YaneuraOuBookMove",
    "YaneuraOuBookEntry",
    "YaneuraOuBook",
    "SbkDiagnostics",
    "SbkOpenProgress",
    "SbkEval",
    "SbkMove",
    "SbkEntry",
    "SbkBook",
    "MemoryBook",
    "StaticBook",
    "BookBuilder",
    "book_key_from_position",
    "book_key_after",
    "book_builder_from_game_record",
]
