from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Literal, TypedDict

from rsshogi.core import Board, Move, Move32

EngineExtraValue = str | int | float | bool
StrictMode = Literal["strict", "permissive"]

class TimeControlDict(TypedDict, total=False):
    base_seconds: int
    byoyomi_seconds: int
    increment_seconds: int

class EngineInfoDict(TypedDict, total=False):
    eval: int | None
    depth: int | None
    nodes: int | None
    seldepth: int | None
    extras: dict[str, EngineExtraValue]

class MoveEntryDict(TypedDict, total=False):
    move: MoveEntry | Move32 | Move | int | str
    time_ms: int | None
    comment: str | None
    engine_info: EngineInfo | EngineInfoDict | None

class RecordMetadataDict(TypedDict, total=False):
    event: str | None
    site: str | None
    black_player: str | None
    white_player: str | None
    game_name: str | None
    game_type: str | None
    time_control: TimeControl | TimeControlDict | str | None
    black_time_control: TimeControl | TimeControlDict | str | None
    white_time_control: TimeControl | TimeControlDict | str | None
    max_moves: int | None
    impasse_rule: str | None
    start_date: str | None
    end_date: str | None
    updated_date: str | None
    comment: str | None
    attributes: dict[str, str]

class GameResultInfoDict(TypedDict, total=False):
    result: int | str | GameResult
    ply_count: int
    reason: str | None
    end_time_ms: int | None
    end_comment: str | None

class RecordDict(TypedDict, total=False):
    version: int
    init_position_sfen: str
    initial_comment: str | None
    moves: list[MoveEntryDict]
    metadata: RecordMetadata | RecordMetadataDict
    result: GameResultInfoDict | int | str | GameResult

class GameResult:
    value: int
    name: str
    __members__: dict[str, GameResult]
    BLACK_WIN: GameResult
    WHITE_WIN: GameResult
    DRAW_BY_REPETITION: GameResult
    ERROR: GameResult
    BLACK_WIN_BY_DECLARATION: GameResult
    WHITE_WIN_BY_DECLARATION: GameResult
    DRAW_BY_MAX_PLIES: GameResult
    BLACK_WIN_BY_FORFEIT: GameResult
    WHITE_WIN_BY_FORFEIT: GameResult
    DRAW_BY_IMPASSE: GameResult
    BLACK_WIN_BY_TRY_RULE: GameResult
    WHITE_WIN_BY_TRY_RULE: GameResult
    INVALID: GameResult
    BLACK_WIN_BY_ILLEGAL_MOVE: GameResult
    WHITE_WIN_BY_ILLEGAL_MOVE: GameResult
    BLACK_WIN_BY_TIMEOUT: GameResult
    WHITE_WIN_BY_TIMEOUT: GameResult
    PAUSED: GameResult
    def __init__(self, value: int) -> None: ...
    @classmethod
    def from_str(cls, name: str) -> GameResult: ...
    def is_black_win(self) -> bool: ...
    def is_white_win(self) -> bool: ...
    def is_draw(self) -> bool: ...
    def is_win(self) -> bool: ...
    def is_win_by_declaration(self) -> bool: ...
    def is_win_by_try_rule(self) -> bool: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TimeControl:
    @property
    def base_seconds(self) -> int: ...
    @property
    def byoyomi_seconds(self) -> int: ...
    @property
    def increment_seconds(self) -> int: ...
    def __init__(self, base_seconds: int, byoyomi_seconds: int, increment_seconds: int) -> None: ...
    def to_spec(self) -> str: ...
    @classmethod
    def from_spec(cls, spec: str) -> TimeControl: ...
    @classmethod
    def normalize_spec(cls, spec: str) -> str: ...
    def __repr__(self) -> str: ...

class EngineInfo:
    eval: int | None
    depth: int | None
    nodes: int | None
    seldepth: int | None
    wall_time_ms: int | None
    latency_delta_ms: int | None
    extras: dict[str, EngineExtraValue]
    def __init__(
        self,
        eval: int | None = ...,
        depth: int | None = ...,
        nodes: int | None = ...,
        seldepth: int | None = ...,
        wall_time_ms: int | None = ...,
        latency_delta_ms: int | None = ...,
        extras: dict[str, EngineExtraValue] | None = ...,
    ) -> None: ...
    def set_extra(self, key: str, value: EngineExtraValue) -> None: ...
    def remove_extra(self, key: str) -> EngineExtraValue | None: ...
    def clear_extras(self) -> None: ...
    def __repr__(self) -> str: ...

class MoveEntry:
    @property
    def move(self) -> Move: ...
    comment: str | None
    time_ms: int | None
    engine_info: EngineInfo | None
    def __init__(
        self,
        move: MoveEntry | Move32 | Move | int | str,
        *,
        time_ms: int | None = ...,
        comment: str | None = ...,
        engine_info: EngineInfo | EngineInfoDict | None = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class SpecialMoveEntry:
    @property
    def kind(self) -> str: ...
    @property
    def unknown_name(self) -> str | None: ...
    @property
    def result(self) -> GameResult: ...
    comment: str | None
    time_ms: int | None
    raw: str | None
    def __init__(
        self,
        kind: str,
        result: GameResult | int | str,
        unknown_name: str | None = ...,
        comment: str | None = ...,
        time_ms: int | None = ...,
        raw: str | None = ...,
    ) -> None: ...
    @classmethod
    def from_result(
        cls,
        result: GameResult | int | str,
        time_ms: int | None = ...,
        comment: str | None = ...,
        raw: str | None = ...,
    ) -> SpecialMoveEntry: ...
    def __repr__(self) -> str: ...

class RecordEntry:
    @property
    def kind(self) -> Literal["move", "special"]: ...
    @property
    def move(self) -> MoveEntry | None: ...
    @property
    def special(self) -> SpecialMoveEntry | None: ...
    def __repr__(self) -> str: ...

class GameResultInfo:
    @property
    def result(self) -> GameResult: ...
    @property
    def ply_count(self) -> int: ...
    @property
    def reason(self) -> str | None: ...
    @property
    def end_time_ms(self) -> int | None: ...
    @property
    def end_comment(self) -> str | None: ...
    def __repr__(self) -> str: ...

class RecordNodeId:
    @property
    def raw(self) -> int: ...
    def __init__(self, raw: int) -> None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class RecordMetadataKey:
    EVENT: str
    SITE: str
    BLACK_PLAYER: str
    WHITE_PLAYER: str
    GAME_NAME: str
    GAME_TYPE: str
    START_DATE: str
    END_DATE: str
    UPDATED_DATE: str
    COMMENT: str

class RecordMetadata:
    event: str | None
    site: str | None
    black_player: str | None
    white_player: str | None
    game_name: str | None
    game_type: str | None
    time_control: TimeControl | None
    black_time_control: TimeControl | None
    white_time_control: TimeControl | None
    max_moves: int | None
    impasse_rule: str | None
    start_date: str | None
    end_date: str | None
    updated_date: str | None
    comment: str | None
    attributes: dict[str, str]
    def __init__(
        self,
        event: str | None = ...,
        site: str | None = ...,
        black_player: str | None = ...,
        white_player: str | None = ...,
        game_name: str | None = ...,
        game_type: str | None = ...,
        time_control: TimeControl | None = ...,
        black_time_control: TimeControl | None = ...,
        white_time_control: TimeControl | None = ...,
        max_moves: int | None = ...,
        impasse_rule: str | None = ...,
        start_date: str | None = ...,
        end_date: str | None = ...,
        updated_date: str | None = ...,
        comment: str | None = ...,
        attributes: dict[str, str] | None = ...,
    ) -> None: ...
    def set_attribute(self, key: str, value: str) -> None: ...
    def remove_attribute(self, key: str) -> str | None: ...
    def clear_attributes(self) -> None: ...
    def __repr__(self) -> str: ...

class Record:
    @property
    def init_position_sfen(self) -> str: ...
    initial_comment: str | None
    @property
    def moves(self) -> list[MoveEntry]: ...
    metadata: RecordMetadata
    @property
    def result(self) -> GameResult: ...
    @property
    def result_info(self) -> GameResultInfo: ...
    @property
    def main_terminal(self) -> SpecialMoveEntry | None: ...
    @main_terminal.setter
    def main_terminal(self, value: SpecialMoveEntry) -> None: ...
    @property
    def game_name(self) -> str | None: ...
    @property
    def game_type(self) -> str | None: ...
    @property
    def updated_date(self) -> str | None: ...
    @property
    def black_time_control(self) -> TimeControl | None: ...
    @property
    def white_time_control(self) -> TimeControl | None: ...
    @property
    def end_time_ms(self) -> int | None: ...
    @property
    def end_comment(self) -> str | None: ...
    def __init__(
        self,
        init_position_sfen: str,
        moves: list[MoveEntry] | None = ...,
        metadata: RecordMetadata | None = ...,
        terminal: SpecialMoveEntry | None = ...,
        initial_comment: str | None = ...,
    ) -> None: ...
    @property
    def move_count(self) -> int: ...
    def update_metadata(
        self,
        patch: RecordMetadata | RecordMetadataDict,
        *,
        strict: bool = ...,
    ) -> None: ...
    def set_metadata_attribute(self, key: str, value: str) -> None: ...
    def remove_metadata_attribute(self, key: str) -> str | None: ...
    def clear_metadata_attributes(self) -> None: ...
    def extend_main_line(self, moves: list[MoveEntry]) -> list[int]: ...
    def set_main_terminal(self, terminal: SpecialMoveEntry) -> int: ...
    def to_kif(self) -> str: ...
    def to_ki2(self) -> str: ...
    def to_csa(self) -> str: ...
    def to_jkf(self) -> str: ...
    def to_usi_position(self, *, include_special_tokens: bool = ...) -> str: ...
    def write_kif(self, path: str | bytes | bytearray, encoding: str | None = ...) -> None: ...
    def write_ki2(self, path: str | bytes | bytearray, encoding: str | None = ...) -> None: ...
    def write_csa(self, path: str | bytes | bytearray, encoding: str | None = ...) -> None: ...
    def write_jkf(self, path: str | bytes | bytearray, encoding: str | None = ...) -> None: ...
    def to_pack(self) -> bytes: ...
    def to_sbinpack(
        self,
        *,
        stem_score: int = ...,
        include_main: bool = ...,
        include_variations: bool = ...,
        metadata: bytes | None = ...,
    ) -> bytes: ...
    def root_node_id(self) -> int: ...
    def main_line_ids(self) -> list[int]: ...
    def node_parent(self, node_id: int) -> int | None: ...
    def node_entry(self, node_id: int) -> RecordEntry | None: ...
    def node_move(self, node_id: int) -> MoveEntry | None: ...
    def node_terminal(self, node_id: int) -> SpecialMoveEntry | None: ...
    def children(self, node_id: int) -> list[int]: ...
    def into_editor(self) -> RecordEditor: ...
    def to_dict(self) -> RecordDict: ...
    def to_psv(self, *, include_main: bool = ..., include_variations: bool = ...) -> list[bytes]: ...
    @classmethod
    def from_kif_str(cls, text: str) -> Record: ...
    @classmethod
    def from_ki2_str(cls, text: str) -> Record: ...
    @classmethod
    def from_csa_str(cls, text: str) -> Record: ...
    @classmethod
    def from_jkf_str(cls, text: str) -> Record: ...
    @classmethod
    def from_usi_position(
        cls,
        position: str,
        *,
        allow_special_tokens: bool = ...,
    ) -> Record: ...
    @classmethod
    def from_kif_file(cls, path: str | bytes | bytearray, encoding: str | None = ...) -> Record: ...
    @classmethod
    def from_ki2_file(cls, path: str | bytes | bytearray, encoding: str | None = ...) -> Record: ...
    @classmethod
    def from_csa_file(cls, path: str | bytes | bytearray, encoding: str | None = ...) -> Record: ...
    @classmethod
    def from_jkf_file(cls, path: str | bytes | bytearray, encoding: str | None = ...) -> Record: ...
    @classmethod
    def from_pack(cls, data: bytes | bytearray) -> Record: ...
    @classmethod
    def from_sbinpack(cls, data: bytes | bytearray) -> Record: ...
    @classmethod
    def from_sbinpack_with_metadata(cls, data: bytes | bytearray) -> tuple[Record, bytes]: ...
    @classmethod
    def from_main_line(
        cls,
        init_position_sfen: str,
        moves: list[MoveEntry],
        terminal: SpecialMoveEntry | None = ...,
        metadata: RecordMetadata | None = ...,
        initial_comment: str | None = ...,
    ) -> Record: ...
    @classmethod
    def from_usi_main_line(
        cls,
        init_position_sfen: str,
        usi_moves: list[str],
        result: GameResult | int | str | None = ...,
        move_times_ms: list[int | None] | None = ...,
        evals: list[int | None] | None = ...,
        nodes: list[int | None] | None = ...,
        depths: list[int | None] | None = ...,
        seldepths: list[int | None] | None = ...,
        wall_times_ms: list[int | None] | None = ...,
        latency_deltas_ms: list[int | None] | None = ...,
        metadata: RecordMetadata | None = ...,
        initial_comment: str | None = ...,
    ) -> Record: ...
    @classmethod
    def from_dict(cls, data: RecordDict, *, strict: bool = ...) -> Record: ...
    def __repr__(self) -> str: ...

class RecordEditor:
    @property
    def current_node(self) -> int: ...
    @property
    def position(self) -> Board: ...
    @property
    def position_sfen(self) -> str: ...
    def __init__(self, init_position: str) -> None: ...
    @classmethod
    def from_record(cls, record: Record) -> RecordEditor: ...
    def record(self) -> Record: ...
    def into_record(self) -> Record: ...
    def go_to(self, node_id: int) -> None: ...
    def go_back(self) -> bool: ...
    def go_forward(self, child_index: int = ...) -> bool: ...
    def branch_to(self, child_index: int = ...) -> bool: ...
    def append_move(self, move: MoveEntry) -> int: ...
    def append_special(self, special: SpecialMoveEntry) -> int: ...
    def __repr__(self) -> str: ...

@dataclass(slots=True)
class RecordMetadataBuilder:
    event: str | None = ...
    site: str | None = ...
    black_player: str | None = ...
    white_player: str | None = ...
    game_name: str | None = ...
    game_type: str | None = ...
    time_control: TimeControl | None = ...
    black_time_control: TimeControl | None = ...
    white_time_control: TimeControl | None = ...
    max_moves: int | None = ...
    impasse_rule: str | None = ...
    start_date: str | None = ...
    end_date: str | None = ...
    updated_date: str | None = ...
    comment: str | None = ...
    attributes: dict[str, str] = ...
    def build(self) -> RecordMetadata: ...

@dataclass(slots=True)
class RecordBuilder:
    init_position_sfen: str
    moves: list[MoveEntry] = ...
    metadata: RecordMetadata | RecordMetadataBuilder | None = ...
    terminal: SpecialMoveEntry | None = ...
    initial_comment: str | None = ...
    def build(self) -> Record: ...

def decode_pack(data: bytes | bytearray) -> list[Record]: ...
def decode_pack_file(path: str | bytes | bytearray) -> list[Record]: ...
def decode_sbinpack(data: bytes | bytearray) -> list[tuple[Record, bytes]]: ...
def decode_sbinpack_file(path: str | bytes | bytearray) -> list[tuple[Record, bytes]]: ...
def write_pack(records: Sequence[Record]) -> bytes: ...
def write_pack_file(path: str | bytes | bytearray, records: Sequence[Record]) -> None: ...
def write_sbinpack(
    records: Sequence[Record],
    *,
    stem_score: int = ...,
    include_main: bool = ...,
    include_variations: bool = ...,
    metadatas: Sequence[bytes | None] | None = ...,
) -> bytes: ...
def write_sbinpack_file(
    path: str | bytes | bytearray,
    records: Sequence[Record],
    *,
    stem_score: int = ...,
    include_main: bool = ...,
    include_variations: bool = ...,
    metadatas: Sequence[bytes | None] | None = ...,
) -> None: ...
